name: Scheduled dependencies update
on:
  schedule:
    - cron: '0 15 * * 2'
jobs:
  update-deps:
    name: Update Node dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: neverendingqs/gh-action-node-update-deps@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump-version: patch                 # defaults to not bumping the package version
          package-manager: yarn               # defaults to 'npm'
          git-user-email: tim.miller@preparesoftware.com # defaults to '41898282+github-actions[bot]@users.noreply.github.com'
          git-user-name: timothymiller                 # defaults to 'github-actions[bot]'
          pre-commit-script: npm run build    # defaults to not running anything
          pull-request-labels: dependencies           # defaults to 'dependencies'
          target-version: latest               # defaults to 'latest'